
import React from 'react';

interface GeneratedImageDisplayProps {
  imageUrl: string;
  prompt: string;
}

const GeneratedImageDisplay: React.FC<GeneratedImageDisplayProps> = ({ imageUrl, prompt }) => {
  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-2xl font-semibold mb-4 text-gray-100 text-center">
          Your Echo Image
        </h3>
        <div className="flex justify-center p-2 bg-gradient-to-br from-gray-700 to-gray-800 rounded-lg shadow-inner">
          <img 
            src={imageUrl} 
            alt="Generated by AI" 
            className="rounded-md shadow-2xl max-w-full sm:max-w-md md:max-w-lg max-h-[500px] object-contain border-2 border-purple-500/70" 
          />
        </div>
      </div>
      <div>
        <h4 className="text-xl font-medium mb-2 text-gray-200">Generation Prompt:</h4>
        <p className="bg-gray-700/70 p-4 rounded-md text-gray-300 text-sm whitespace-pre-wrap break-words shadow-inner leading-relaxed">
          {prompt}
        </p>
      </div>
    </div>
  );
};

export default GeneratedImageDisplay;
